FROM quay.io/redhat-github-actions/runner:latest as runner

USER root

RUN dnf module install -y nodejs:14


RUN dnf install buildah -y

# Set Buildah to work in non-root environments
RUN echo "containers: { storage-driver: \"vfs\" }" >> /etc/containers/storage.conf

# Set entrypoint for the runner
ENTRYPOINT ["/actions-runner/bin/runsvc.sh"]