name: CD with Docker

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: self-hosted  # Use the self-hosted runner

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Pull the latest Docker image from Docker Hub
    - name: Pull latest Docker image
      run: |
        docker pull ${{ secrets.DOCKER_USERNAME }}/node-web-app:latest

    # Check if the container is already running
    - name: Check if container is running
      id: is_running
      run: |
        if [ $(docker ps -q -f name=node-web-app) ]; then
          echo "container-running=true" >> $GITHUB_ENV
        else
          echo "container-running=false" >> $GITHUB_ENV
        fi

    # Stop and remove the existing container if running
    - name: Stop and remove running container
      if: env.container-running == 'true'
      run: |
        docker stop node-web-app
        docker rm node-web-app

    # Run the new container
    - name: Run new Docker container
      run: |
        docker run -d -p 8080:8080 --name node-web-app ${{ secrets.DOCKER_USERNAME }}/node-web-app:latest